### ISSUE TITLE
Discussion on future project development and implementation ideas

### ISSUE THREAD

**Issue by skytin1004** [Imperial-EE-Microsoft/co_op_translator#5]
@timothycdc I would like to clarify and plan the implementation strategies for our project going forward. If you have time, could you please review this issue? If there are any potential issues or if you have other ideas, I would appreciate it if you could share your thoughts!

## 1. CLI implementation for translation commands:

- I'm considering implementing a command line interface (CLI) that allows users to generate translations directly from the terminal by typing commands.
- Example commands:
  - `translate --languages es fr de`: Generates translations for the given language codes.
  - `translate --languages all`: Generates translations for all currently supported language codes (as listed in the `font-mappings.yml` file).
- The CLI would work from the root of the current terminal session, find the necessary files and generate the translation output accordingly.

I would appreciate your thoughts on this approach, especially regarding its feasibility and possible improvements.

## 2. File naming convention for translated images:

- In the `github-app` repository, image filenames for translations are formatted as `readme_img<hash>.fr.png` where `<hash>` is included in the name.
- I'm wondering if including `<hash>` is necessary, especially considering future features like automatically updating translated images or deleting unused ones. Having `<hash>` in the filename might make it more difficult to identify and manage these files.

- I’m interested in hearing your opinion on whether `<hash>` is essential or if we could simplify the naming convention to make future management tasks easier.

Looking forward to your feedback and suggestions!

**Comment by timothycdc** [comment]
Hi @skytin1004, apologies for the delay in the PR/ reviews.
I like the CLI implementation, perhaps you can add a flag to specify the folder containing the files to translate?

In terms of hash, it was a design decision for the proof of concept because on GitHub, it is allowed to have a markdown file that contains images having same filename, as long as they were in different folders e.g. `readme.md` has images `./feature1/screenshot.png` `./feature2/screenshot.png`. However, as part of the translation process, all translated images get placed together in the same folder, resulting in a collision of filenames.

I am not sure if you want to allow for this edge case, or assume that all images are given unique names for a codebase. Or instead of hashing all images, rename files *only if there is a collision*.

I'll leave the implementation up to your decision.

**Comment by skytin1004** [comment]
@timothycdc Thank you for your feedback!
